#!/usr/bin/env python3
"""
get_fig_ch5_entanglement_scaling_analog.py
==========================================
Half-chain entanglement entropy S_A(N/2) versus system size N for ANALOG
(Trotterized Hamiltonian) evolution of an XX chain in a random x-field, at
fixed evolution times t = 0, 2, 4, 6, 8, 10.

This script computes panel (b), and is also the PLOTTING DRIVER that assembles
the finished two-panel figure: it reads the cached panel-(a) data produced by
get_fig_ch5_entanglement_scaling_digital.py (brickwork Ry+CNOT circuit at fixed
depths) and draws both panels side by side.

Produces:  Figure 5.3 of Chapter 5 (label fig:entanglement_scaling in
           ch5_designs.tex), written to

               figures/ch5/fig_ch5_entanglement_scaling.pdf   (+ .png)

============================================================
PHYSICS BACKGROUND
============================================================
"ANALOG" here means continuous-time evolution generated by a Hamiltonian,

    |psi(t)> = e^{-i H t} |psi(0)>,

as opposed to the "digital" picture of panel (a), where the state is driven by
a discrete circuit of elementary gates and the control parameter is the circuit
depth L rather than a physical time t. The two panels are the same experiment
run with the two different notions of "how far the dynamics has gone": depth on
the left, time on the right.

The observable is the von Neumann entropy of the left half of the chain,

    S_A = -Tr rho_A ln rho_A,      A = first N/2 qubits,

plotted in bits (the code divides by ln 2).

WHAT THE SCALING SHOWS
    An entropy that grows in proportion to the size of the subsystem, S_A ~ N/2,
    is a VOLUME LAW: the state is entangled across the cut as strongly as its
    size permits, in contrast to the AREA LAW S_A ~ const obeyed by ground
    states of local gapped Hamiltonians and by shallow (fixed, N-independent)
    circuits. Plotted against N at fixed t, an area law is a flat line and a
    volume law is a line of slope 1/2.

THE PAGE VALUE
    The gray dashed reference is Page's exact average entropy of a subsystem of
    a Haar-random pure state (page_entropy() below). It is the entropy a
    *maximally scrambled* state of this size would have, and it sits slightly
    BELOW the naive maximum (N/2) ln 2 by the well-known -1/2 deficit at an
    equal bipartition. It is the natural finite-N benchmark for "as entangled as
    a random state", and it is what both panels are converging toward.

THE TAKEAWAY (this is the point of the figure in the text)
    Both the digital circuit and the analog Hamiltonian evolution drive S_A up
    to the Page scale as depth or time increases. The chapter uses this as a
    NEGATIVE result: scalar entanglement entropy saturates at the Page value for
    both, so it cannot separate the classically tractable from the classically
    hard. Reaching the Page value is necessary for scrambling but nowhere near
    sufficient, which is what motivates the finer diagnostics (entanglement
    SPECTRUM shape, and nonstabilizerness) introduced right after this figure.
    The figure is meant to look "successful" for both curves. That is the joke.

============================================================
THE MODEL
============================================================
    H = sum_{i=1}^{N-1} (sx_i sx_{i+1} + sy_i sy_{i+1})  +  sum_{i=1}^{N} h_i sx_i

with open boundary conditions and quenched random fields h_i ~ Uniform[-1, 1].

WHY THE FIELD POINTS ALONG x (and not z)
    The bare XX chain is integrable: under a Jordan-Wigner transformation the
    flip-flop term is a free-fermion hopping term, and a field along z would
    stay quadratic (it is just a fermion number operator), leaving the model
    exactly solvable and NOT scrambling. A field along x is not quadratic in the
    fermions: sx_i carries the Jordan-Wigner string, so it is a nonlocal,
    interacting term. Pointing the field along x is therefore the whole reason
    this model scrambles at all, and the randomness in h_i additionally removes
    any residual spatial symmetry. Rotating the field to z would silently turn
    the physics of this panel off.

INITIAL STATE
    A GHZ state, (|00...0> + |11...1>)/sqrt(2), for both panels. Note its
    half-chain entropy is exactly ln 2 (one bit) for every N, which is why the
    t = 0 curve in the figure is a FLAT line at 1 rather than at 0. It is
    entangled but only by a single bit: a clean illustration that "entangled"
    and "scrambled" are different statements.

============================================================
ALGORITHM (per data point)
============================================================
For each system size N in {6, 8, ..., 20} and each time t in {0, 2, ..., 10}:

  1. Draw the disorder: h_i ~ Uniform[-1,1], from a generator seeded with
     SEED + N, so the fields are reproducible and every time t at a given N
     sees the SAME disorder realization (the curves at one N are one physical
     sample watched at six moments, not six unrelated samples).

  2. Evolve: n_steps = round(t/dt) first-order Trotter steps applied to the GHZ
     state (evolve_xx_trotter). See TROTTER DECOMPOSITION below.

  3. Reduced density matrix and entropy (entanglement_entropy): reshape the
     statevector to a matrix across the cut, form rho_A, diagonalize, and sum
     -lambda ln lambda.

  4. Cache the point immediately (incremental np.savez after every point).

NOTE ON AVERAGING: there is NO disorder average. Each (N, t) point is a SINGLE
realization of h_i. This is deliberate and adequate here because S_A is
self-averaging at these sizes (the sample-to-sample spread is invisible on the
scale of the plot, which spans 0 to N/2 bits), and because the figure is making
a qualitative point about the trend toward the Page value, not a quantitative
claim about a mean. Do not read the markers as ensemble means.

============================================================
TROTTER DECOMPOSITION: KEY IDEA
============================================================
Computing e^{-iHt} as a dense matrix exponential would cost O(D^2) memory with
D = 2^N, which is already 2^40 complex numbers at N = 20 and hopeless. Instead
each time step dt is split into a SEQUENCE OF LOCAL GATES acting on the
statevector, which never leaves O(D) memory:

    e^{-iH dt} ~= [prod_i e^{-i dt h_i sx_i}]
                  . [prod_{i even} e^{-i dt H_XX^{i,i+1}}]
                  . [prod_{i odd}  e^{-i dt H_XX^{i,i+1}}]

This is a first-order Suzuki-Trotter splitting: the error per step is O(dt^2),
accumulating to O(dt) over a fixed total time t. Since the terms of H do not
commute, this is an approximation, and dt = 0.05 is chosen small enough that the
Trotter error is far below the resolution of the figure.

THE STRUCTURAL POINT
    The Trotter decomposition maps Hamiltonian evolution onto exactly the same
    BRICKWORK structure as the digital circuit of panel (a):
      - 1-qubit gates:  exp(-i dt h_i sx)                 <->  Rx rotation
      - 2-qubit gates:  exp(-i dt (sx@sx + sy@sy))        <->  XX flip-flop gate
    So the same einsum-based gate application is reused, at O(N 2^N) per Trotter
    step. This is not just an implementation convenience: it is the reason the
    two panels are a fair comparison at all, since "analog" and "digital" here
    are literally the same brickwork with different gates.

============================================================
TROTTER GATE DERIVATIONS
============================================================
1-QUBIT: transverse field term h_i sx_i
    Since sx^2 = I, the exponential closes in the obvious way:

        exp(-i dt h sx) = cos(dt h) I - i sin(dt h) sx

              [  cos(dt h)    -i sin(dt h) ]
            = [ -i sin(dt h)   cos(dt h)   ]

    which is an Rx(2 dt h) rotation.

2-QUBIT: XX interaction sx_i sx_{i+1} + sy_i sy_{i+1}
    In the basis {|00>, |01>, |10>, |11>}:

        sx@sx + sy@sy = 2 (|01><10| + |10><01|)

    a "flip-flop" (partial swap) interaction. The |00> and |11> sectors are
    annihilated by it (the two spins are aligned, so there is nothing to flip)
    and therefore pass through the exponential untouched. On the {|01>, |10>}
    block the generator is just 2 sx, so the same identity as above gives:

            [ 1       0             0        0 ]
            [ 0    cos(2 dt)   -i sin(2 dt)  0 ]
            [ 0  -i sin(2 dt)   cos(2 dt)    0 ]
            [ 0       0             0        1 ]

============================================================
IMPLEMENTATION NOTES (the "why")
============================================================
STATEVECTOR, NOT DENSITY MATRIX; NO SPARSE HAMILTONIAN
    The Hamiltonian is never built, sparse or otherwise. Only the 2^N
    statevector exists, and the gates are applied to it in place. A sparse H
    plus expm_multiply would work but would be strictly worse here: the gate
    sequence IS the propagator, and it costs O(N 2^N) per step with no Krylov
    machinery and no matrix at all.

STATEVECTOR AS A RANK-N TENSOR
    psi is reshaped from (2^N,) to (2,)*N so that a gate on qubit j is a tensor
    contraction over axis j, done with einsum. This is why _subs_1q/_subs_2q
    precompute the subscript strings: they are pure string manipulation and
    would otherwise be rebuilt inside the time-stepping loop.

    _AX has 21 letters, which caps this scheme at N <= 21. SYSTEM_SIZES stops at
    N = 20, so there is one letter of headroom; raising the maximum N requires
    extending _AX first.

GATES ARE BUILT ONCE PER (N, t), NOT PER STEP
    Every Trotter step applies the identical gate set, since H is time
    independent. rx_gates and the single universal xx_gate are therefore hoisted
    out of the stepping loop. The XX gate is universal across bonds because the
    coupling is uniform; only the field gates differ from site to site.

RESHAPE CONVENTION FOR THE PARTIAL TRACE
    entanglement_entropy exploits the fact that a bipartition of a statevector
    into A (first k qubits, contiguous, and this is what makes it valid) and B
    is just a MATRIX RESHAPE: psi -> C of shape (2^k, 2^(N-k)), the coefficient
    matrix across the cut, whence rho_A = C C^dagger. No explicit partial trace
    and no 2^N x 2^N object is ever formed.

    k_eff = min(k, N-k) ensures rho_A is built on the SMALLER side of the cut,
    which is what bounds memory: the spectrum is identical on both sides, so
    diagonalizing the small one is free of charge. The k > N-k branch reshapes
    to (2^(N-k), 2^k) and transposes, because the qubit ordering forces B to be
    the fast index in that case. In this figure k = N//2 with N even, so the two
    sides are equal and only the first branch is ever taken; the second exists
    so the routine stays correct if reused off-center.

EIGENVALUE CLIPPING TO AVOID log(0)
    rho_A of a Trotter-evolved state has many exactly-zero (or slightly
    negative, by roundoff) eigenvalues, and 0*log(0) is NaN rather than the
    mathematically correct 0. eigvalsh is therefore clipped at 1e-30 before the
    log. This both kills the NaN and neutralizes negative roundoff eigenvalues.
    The bias introduced is at most ~1e-30 * 69 per eigenvalue, i.e. utterly
    negligible against entropies of order 1 to 10.

FLOAT64 IS MANDATORY
    JAX_ENABLE_X64 is set BEFORE jax is imported (it is read at import time, so
    setting it later silently does nothing) and all arrays are complex128.
    Entropies are computed from eigenvalues that span many orders of magnitude
    and float32 would visibly corrupt the small-eigenvalue tail.

PAGE FORMULA COMPUTED EXACTLY, NOT SAMPLED
    page_entropy() evaluates Page's closed-form expression by direct summation.
    It is an INDEPENDENT analytic benchmark: the dashed curve comes from the
    formula, the markers come from actual Trotter evolution, and nothing in this
    script samples the Page distribution to "verify" the Page formula.

============================================================
RUNTIME / MEMORY
============================================================
MEMORY is dominated by the statevector and a small number of einsum temporaries:

    N=16: D=65536,     psi = 1 MB,    rho_A = 256x256      (instant)
    N=20: D=1048576,   psi = 16 MB,   rho_A = 1024x1024    (dominates runtime)

so the whole sweep is a few hundred MB at worst. The cost is TIME, not memory:
work scales as O(N 2^N) per Trotter step, times n_steps = t/dt (200 steps at
t = 10), times ~2N gates per step. N = 20 at t = 10 is roughly 100x the cost of
N = 14 at t = 10, and the largest few (N, t) points dominate the total. Expect
minutes overall on CPU, less with a GPU-backed JAX. The script prints the wall
time of every point as it goes, so progress is visible.

CACHING / CLI
    Data cache:  data/ch5/entropy_vs_N_analog.npz   (this script, panel (b))
                 data/ch5/entropy_vs_N_depths.npz   (the digital script, panel (a))

    Results are saved incrementally after EVERY (N, t) point, and a rerun
    resumes by recomputing only the NaN entries. A killed run therefore loses at
    most one data point.

    --regenerate   ignore the cache and recompute every point from scratch
    --plot-only    skip all computation and just redraw from the cache
                   (errors out if the analog cache is absent)

    DATA_DIR and the figure OUTPUT path are both resolved from __file__, so
    this script may be run from any working directory and always reads the
    digital script's panel-(a) cache (entropy_vs_N_depths.npz) from the same
    data/ch5 folder.

============================================================
OUTPUT FILENAME COLLISION (read before rerunning)
============================================================
This script and get_fig_ch5_entanglement_scaling_digital.py BOTH write

    figures/ch5/fig_ch5_entanglement_scaling.pdf

but they write DIFFERENT figures to it. This script writes the two-panel (a)+(b)
figure that the book's Fig. 5.3 caption describes; the digital script writes a
one-panel, depths-only version. Whichever runs LAST wins.

    ==> This script must be run LAST. Run the digital script first (it produces
        the panel-(a) cache this script reads), then this one.

If the digital data cache is missing, plot_figure() falls back to
plot_analog_only(), which writes a DIFFERENT file,
figures/ch5/fig_ch5_entanglement_analog.pdf (single analog panel only). That
file is not the book figure and is not referenced by any chapter; it exists only
so this script can still produce something standalone. If it appears in
figures/ch5/, that is a signal that the digital cache was missing and Fig. 5.3
was not regenerated.
"""

import os, sys, time as timer, argparse
from pathlib import Path

os.environ["XLA_PYTHON_CLIENT_PREALLOCATE"] = "false"
os.environ["JAX_ENABLE_X64"] = "1"

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

sys.path.insert(0, str(Path(__file__).resolve().parent))
from plot_style import apply_book_style, load_or_compute, panel_label

import jax
import jax.numpy as jnp

CDT = jnp.complex128

# ══════════════════════════════════════════════════════════════════
#  CONFIGURATION
# ══════════════════════════════════════════════════════════════════

SYSTEM_SIZES = list(range(6, 21, 2))      # N = 6, 8, ..., 20
EVOLUTION_TIMES = [0, 2, 4, 6, 8, 10]     # fixed times t
DT = 0.05                                  # Trotter step size
SEED = 42                                  # reproducible random fields
DATA_DIR = Path(__file__).resolve().parent / "data" / "ch5"
OUTPUT_DIR = Path(__file__).resolve().parent.parent / "figures" / "ch5"
DATA_DIR.mkdir(parents=True, exist_ok=True)
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


# ══════════════════════════════════════════════════════════════════
#  EINSUM SUBSCRIPT GENERATION  (same as digital circuit scripts)
# ══════════════════════════════════════════════════════════════════
#
#  The statevector |ψ⟩ is stored as a rank-N tensor of shape (2,)*N.
#  These functions generate the einsum strings for applying 1-qubit
#  and 2-qubit gates via tensor contraction:
#
#    1-qubit:  G[j'] ψ[..., j, ...] → ψ'[..., j', ...]
#    2-qubit:  G[c', t', c, t] ψ[..., c, ..., t, ...] → ψ'[..., c', ..., t', ...]
#
# ══════════════════════════════════════════════════════════════════

# 21 index letters: this caps the scheme at N <= 21 (SYSTEM_SIZES stops at 20).
_AX = "abcdefghijklmnopqrstu"

def _subs_1q(N):
    """Einsum subscripts for 1-qubit gates on each of N qubits."""
    subs = []
    for j in range(N):
        ax = list(_AX[:N])
        out = list(ax)
        new = chr(ord('A') + j)
        out[j] = new
        subs.append(f"{new}{ax[j]},{''.join(ax)}->{''.join(out)}")
    return subs

def _subs_2q(N):
    """Einsum subscripts for 2-qubit gates on all qubit pairs."""
    subs = {}
    for c in range(N):
        for t in range(N):
            if c == t: continue
            ax = list(_AX[:N])
            out = list(ax)
            C, T = chr(ord('A')+c), chr(ord('A')+t)
            out[c], out[t] = C, T
            subs[(c,t)] = f"{C}{T}{ax[c]}{ax[t]},{''.join(ax)}->{''.join(out)}"
    return subs


# ══════════════════════════════════════════════════════════════════
#  TROTTER GATE CONSTRUCTION
# ══════════════════════════════════════════════════════════════════
#
#  For a Trotter step of size dt, we build:
#
#    1. N single-qubit gates:  Rx_i = exp(-i·dt·h_i·σ_x)
#       Each depends on the local random field h_i.
#
#    2. One universal 2-qubit gate: XX(dt) = exp(-i·dt·(σ_x⊗σ_x + σ_y⊗σ_y))
#       This is the SAME for all pairs (only the coupling constant matters).
#
# ══════════════════════════════════════════════════════════════════

def _build_rx_gates(h_fields, dt):
    """
    Build N single-qubit Rx gates for the transverse field term.

    exp(-i·dt·h·σ_x) = [[cos(dt·h), -i·sin(dt·h)],
                         [-i·sin(dt·h), cos(dt·h)]]

    Returns a list of N (2,2) JAX arrays.
    """
    gates = []
    for h in h_fields:
        c = jnp.cos(dt * h)
        s = jnp.sin(dt * h)
        gates.append(jnp.array([[c, -1j*s], [-1j*s, c]], dtype=CDT))
    return gates


def _build_xx_gate(dt):
    """
    Build the 2-qubit XX gate for one Trotter step.

    exp(-i·dt·(σ_x⊗σ_x + σ_y⊗σ_y))

    In the {|00⟩, |01⟩, |10⟩, |11⟩} basis:
      |00⟩ → |00⟩                   (unaffected)
      |01⟩ → cos(2dt)|01⟩ - i·sin(2dt)|10⟩  (flip-flop)
      |10⟩ → -i·sin(2dt)|01⟩ + cos(2dt)|10⟩
      |11⟩ → |11⟩                   (unaffected)

    Returns a (2,2,2,2) JAX array for einsum application.
    """
    c = jnp.cos(2.0 * dt)
    s = jnp.sin(2.0 * dt)

    # Build 4×4 matrix, then reshape to (2,2,2,2) tensor
    gate = jnp.array([
        [1,     0,       0,    0],
        [0,     c,    -1j*s,   0],
        [0,  -1j*s,      c,   0],
        [0,     0,       0,    1],
    ], dtype=CDT).reshape(2, 2, 2, 2)
    return gate


# ══════════════════════════════════════════════════════════════════
#  TROTTERIZED TIME EVOLUTION
# ══════════════════════════════════════════════════════════════════
#
#  One Trotter step of the first-order Suzuki–Trotter decomposition:
#
#    e^{-iĤ·dt} ≈ [∏_i Rx_i(dt·h_i)] · [∏_{i∈even} XX_{i,i+1}(dt)]
#                                        · [∏_{i∈odd}  XX_{i,i+1}(dt)]
#
#  This has EXACTLY the same brickwork structure as the digital circuit:
#    Ry gates      →  Rx gates (field-dependent)
#    CNOT gates    →  XX gates (interaction-dependent)
#
#  For total time T, we apply n_steps = round(T/dt) Trotter steps.
#
# ══════════════════════════════════════════════════════════════════

def evolve_xx_trotter(N, t_total, h_fields, dt=DT):
    """
    Evolve GHZ state under XX Hamiltonian via Trotterization.

    Parameters
    ----------
    N : int — number of qubits
    t_total : float — total evolution time
    h_fields : array of shape (N,) — random transverse field strengths
    dt : float — Trotter step size

    Returns
    -------
    psi : array of shape (2^N,) — evolved statevector
    """
    # t=0: return the bare GHZ state (no steps). Its half-chain entropy is
    # exactly ln 2 for every N, giving the flat t=0 line in the figure.
    if t_total == 0:
        D = 1 << N
        psi = jnp.zeros(D, dtype=CDT)
        psi = psi.at[0].set(1/jnp.sqrt(2.0))
        psi = psi.at[D-1].set(1/jnp.sqrt(2.0))
        return psi

    # Number of Trotter steps
    n_steps = max(1, round(t_total / dt))

    # Precompute gates and einsum subscripts (done once, reused per step)
    sub1 = _subs_1q(N)
    sub2 = _subs_2q(N)
    rx_gates = _build_rx_gates(h_fields, dt)     # N single-qubit gates
    xx_gate  = _build_xx_gate(dt)                 # one universal 2-qubit gate
    even = [(j, j+1) for j in range(0, N-1, 2)]  # even-odd brickwork
    odd  = [(j, j+1) for j in range(1, N-1, 2)]

    # GHZ initial state
    D = 1 << N
    psi = jnp.zeros(D, dtype=CDT)
    psi = psi.at[0].set(1/jnp.sqrt(2.0))
    psi = psi.at[D-1].set(1/jnp.sqrt(2.0))

    # ── Trotter time-stepping ────────────────────────────────────
    for step in range(n_steps):
        p = psi.reshape((2,)*N)

        # 1. Apply single-qubit field gates: exp(-i·dt·h_i·σ_x)
        for j in range(N):
            p = jnp.einsum(sub1[j], rx_gates[j], p)

        # 2. Apply XX gates on even pairs
        for c, t in even:
            p = jnp.einsum(sub2[(c, t)], xx_gate, p)

        # 3. Apply XX gates on odd pairs
        for c, t in odd:
            p = jnp.einsum(sub2[(c, t)], xx_gate, p)

        psi = p.reshape(D)

    return psi


# ══════════════════════════════════════════════════════════════════
#  ENTANGLEMENT ENTROPY
# ══════════════════════════════════════════════════════════════════

def entanglement_entropy(psi, N, k):
    """Von Neumann entropy S_A for subsystem A = first k qubits."""
    # Build rho on the SMALLER side of the cut; both sides share a spectrum.
    k_eff = min(k, N - k)
    m = 1 << k_eff
    n = (1 << N) >> k_eff
    if k <= N - k:
        # A is the slow index already: the bipartition is a plain reshape.
        C = psi.reshape(m, n)
    else:
        # A is the fast index here, so reshape B-major and transpose.
        C = psi.reshape(n, m).T
    rho = jnp.einsum('ab,cb->ac', C, jnp.conj(C))    # rho_A = C C^dagger
    # Clip before the log: zero eigenvalues give NaN, roundoff gives negatives.
    eigs = jnp.clip(jnp.linalg.eigvalsh(rho), 1e-30, None)
    return float(-jnp.sum(eigs * jnp.log(eigs)))


# ══════════════════════════════════════════════════════════════════
#  PAGE'S FORMULA
# ══════════════════════════════════════════════════════════════════

def page_entropy(N, k):
    """Exact Page entropy for N qubits, subsystem of k qubits."""
    # Page: S = sum_{j=d_B+1}^{d_A d_B} 1/j  -  (d_A-1)/(2 d_B),  for d_A <= d_B.
    # Evaluated exactly (not sampled), so the dashed benchmark curve in the
    # figure is analytically independent of the simulated markers.
    d_A = 1 << min(k, N - k)
    d_B = 1 << max(k, N - k)
    S = sum(1.0/j for j in range(d_B + 1, d_A * d_B + 1))
    S -= (d_A - 1) / (2.0 * d_B)
    return S


# ══════════════════════════════════════════════════════════════════
#  DATA GENERATION — WITH INCREMENTAL SAVES
# ══════════════════════════════════════════════════════════════════

def generate_data(regenerate=False):
    t0 = timer.time()

    sa_file = DATA_DIR / "entropy_vs_N_analog.npz"
    Ns = np.array(SYSTEM_SIZES)
    times = np.array(EVOLUTION_TIMES, dtype=float)
    sa = np.full((len(Ns), len(times)), np.nan)
    sa_page = np.full(len(Ns), np.nan)

    # Load partial data if available
    if sa_file.exists():
        old = np.load(sa_file)
        if "sa" in old and old["sa"].shape == sa.shape and not regenerate:
            sa = old["sa"].copy()
            sa_page = old["sa_page"].copy()
            n_done = np.count_nonzero(~np.isnan(sa))
            if n_done == sa.size:
                print(f"  Cached: {sa_file}")
                return
            print(f"  Loaded partial data: {n_done}/{sa.size} values")

    print(f"\n  S_A(N/2) vs N at times t = {list(times)}")
    print(f"  Trotter step dt = {DT},  system sizes: {list(Ns)}\n")

    for i, N in enumerate(Ns):
        k = N // 2

        # Page formula
        if np.isnan(sa_page[i]):
            sa_page[i] = page_entropy(N, k)

        # Random transverse fields (reproducible per N). Drawn ONCE outside the
        # time loop, so every t at this N follows the same disorder realization.
        # Single sample, not a disorder average: see the docstring.
        rng = np.random.default_rng(SEED + N)
        h_fields = rng.uniform(-1, 1, size=N)

        for j, t in enumerate(times):
            if not np.isnan(sa[i, j]):
                continue

            n_steps = max(1, round(t / DT)) if t > 0 else 0
            print(f"    N={N:2d}, t={t:4.1f} ({n_steps:3d} steps): ",
                  end="", flush=True)
            t1 = timer.time()

            psi = evolve_xx_trotter(N, t, h_fields, dt=DT)
            sa[i, j] = entanglement_entropy(psi, N, k)
            dt_wall = timer.time() - t1
            print(f"S/ln2 = {sa[i,j]/np.log(2):.3f}  ({dt_wall:.1f}s)")

            # Incremental save
            np.savez(sa_file, Ns=Ns, times=times, sa=sa, sa_page=sa_page)

    print(f"\n  → {sa_file} (complete)")
    print(f"  Total: {timer.time()-t0:.1f}s")


# ══════════════════════════════════════════════════════════════════
#  PLOTTING — 2-panel: digital (a) + analog (b)
# ══════════════════════════════════════════════════════════════════
#
#  Combines the digital circuit data (from get_fig_ch5_entanglement_
#  scaling.py) with the analog Hamiltonian data into a single
#  2-panel publication figure.
#
# ══════════════════════════════════════════════════════════════════

def plot_figure():
    print("  Plotting combined 2-panel figure...")

    # Load panel-(a) data produced by get_fig_ch5_entanglement_scaling_digital.py.
    # (The warning below names an older filename for that script; the current
    # one is get_fig_ch5_entanglement_scaling_digital.py.)
    dig_file = DATA_DIR / "entropy_vs_N_depths.npz"
    if not dig_file.exists():
        print("  WARNING: digital data not found, run get_fig_ch5_entanglement_scaling.py first")
        print("  Plotting analog-only figure...")
        plot_analog_only()
        return

    data_dig = np.load(dig_file)
    Ns_d     = data_dig["Ns"]
    depths   = data_dig["depths"]
    sa_d     = data_dig["sa"]
    page_d   = data_dig["sa_page"]

    # Load analog data
    data_ana = np.load(DATA_DIR / "entropy_vs_N_analog.npz")
    Ns_a     = data_ana["Ns"]
    times    = data_ana["times"]
    sa_a     = data_ana["sa"]
    page_a   = data_ana["sa_page"]

    LN2 = np.log(2)

    # ── Colour palettes ───────────────────────────────────────────
    colors_d = {0: "#333333", 2: "#2C7FB8", 4: "#7FBC41",
                8: "#FD8D3C", 10: "#D95F02", 16: "#9E4A9C"}
    markers_d = {0: "o", 2: "o", 4: "^", 8: "s", 10: "D", 16: "p"}

    colors_a = {0: "#333333", 2: "#2C7FB8", 4: "#7FBC41",
                6: "#FD8D3C", 8: "#9E4A9C"}
    markers_a = {0: "o", 2: "o", 4: "^", 6: "s", 8: "p"}

    apply_book_style()
    fig, (ax_d, ax_a) = plt.subplots(1, 2, figsize=(12, 5), sharey=True)
    fig.subplots_adjust(wspace=0.08)

    y_max = max(Ns_d[-1], Ns_a[-1]) // 2 + 1

    # ════════════════════════════════════════════════════════════════
    #  Panel (a): Digital circuit — Ry+CNOT brickwork
    # ════════════════════════════════════════════════════════════════

    ax_d.plot(Ns_d, page_d / LN2, "--", color="gray", lw=1.5, alpha=0.6,
              label="Page value", zorder=1)

    for j, L in enumerate(depths):
        L = int(L)
        c = colors_d.get(L, "gray")
        m = markers_d.get(L, "o")
        fc = "white" if L == 0 else c
        ax_d.plot(Ns_d, sa_d[:, j] / LN2, f"-{m}", color=c, lw=1.8,
                  markersize=7, markerfacecolor=fc,
                  markeredgecolor=c, markeredgewidth=1.5,
                  zorder=3, label=f"$L = {L}$")

    j_N = len(depths)
    ax_d.plot(Ns_d, sa_d[:, j_N] / LN2, "x--", color="#E63946", lw=2.2,
              markersize=9, markeredgewidth=2.5,
              zorder=5, label=r"$L = N$")

    ax_d.set_xlabel(r"System size $N$")
    ax_d.set_ylabel(r"Entanglement entropy $S_{\mathrm{vN}}\,/\,\ln 2$")
    ax_d.set_xlim(SYSTEM_SIZES[0] - 0.5, SYSTEM_SIZES[-1] + 0.5)
    ax_d.set_ylim(0, y_max)
    ax_d.set_xticks(SYSTEM_SIZES)
    ax_d.legend(loc="upper left", framealpha=0.9, fontsize=11)
    ax_d.text(0.97, 0.95, r"$\mathbf{(a)}$", transform=ax_d.transAxes,
              fontsize=14, va="top", ha="right")

    # ════════════════════════════════════════════════════════════════
    #  Panel (b): Analog evolution — XX + random field (Trotterized)
    # ════════════════════════════════════════════════════════════════

    ax_a.plot(Ns_a, page_a / LN2, "--", color="gray", lw=1.5, alpha=0.6,
              label="Page value", zorder=1)

    for j, t in enumerate(times[:-1]):
        t_int = int(t)
        c = colors_a.get(t_int, "gray")
        m = markers_a.get(t_int, "o")
        fc = "white" if t_int == 0 else c
        ax_a.plot(Ns_a, sa_a[:, j] / LN2, f"-{m}", color=c, lw=1.8,
                  markersize=7, markerfacecolor=fc,
                  markeredgecolor=c, markeredgewidth=1.5,
                  zorder=3, label=f"$t = {t_int}$")

    t_last = int(times[-1])
    ax_a.plot(Ns_a, sa_a[:, -1] / LN2, "x--", color="#E63946", lw=2.2,
              markersize=9, markeredgewidth=2.5,
              zorder=5, label=f"$t = {t_last}$")

    ax_a.set_xlabel(r"System size $N$")
    ax_a.set_xlim(SYSTEM_SIZES[0] - 0.5, SYSTEM_SIZES[-1] + 0.5)
    ax_a.set_ylim(0, y_max)
    ax_a.set_xticks(SYSTEM_SIZES)
    ax_a.legend(loc="upper left", framealpha=0.9, fontsize=11)
    ax_a.text(0.97, 0.95, r"$\mathbf{(b)}$", transform=ax_a.transAxes,
              fontsize=14, va="top", ha="right")

    # ── Save ─────────────────────────────────────────────────────
    # This is Fig. 5.3 of the book. The digital script writes the SAME path with
    # a one-panel figure, so this script must run last. See the docstring.
    outpath = OUTPUT_DIR / "fig_ch5_entanglement_scaling.pdf"
    fig.savefig(outpath)
    fig.savefig(outpath.with_suffix(".png"))
    print(f"    → PDF: {outpath}")
    print(f"    → PNG: {outpath.with_suffix('.png')}")
    plt.close(fig)


def plot_analog_only():
    """
    Fallback: plot only the analog panel if digital data is unavailable.

    Writes fig_ch5_entanglement_analog.pdf, a DIFFERENT file that is not the
    book figure and is not referenced by any chapter.
    """
    data = np.load(DATA_DIR / "entropy_vs_N_analog.npz")
    Ns, times, sa, sa_page = data["Ns"], data["times"], data["sa"], data["sa_page"]
    LN2 = np.log(2)

    colors = {0: "#7FCDBB", 2: "#2C7FB8", 4: "#7FBC41",
              6: "#FD8D3C", 8: "#9E4A9C"}
    markers = {0: "o", 2: "o", 4: "^", 6: "s", 8: "p"}

    apply_book_style()
    fig, ax = plt.subplots(1, 1, figsize=(6.5, 5))
    ax.plot(Ns, sa_page / LN2, "--", color="gray", lw=1.5, alpha=0.6, label="Page value")

    for j, t in enumerate(times[:-1]):
        t_int = int(t)
        c = colors.get(t_int, "gray")
        m = markers.get(t_int, "o")
        fc = "white" if t_int == 0 else c
        ax.plot(Ns, sa[:, j] / LN2, f"-{m}", color=c, lw=1.8,
                markersize=7, markerfacecolor=fc, markeredgecolor=c,
                markeredgewidth=1.5, label=f"$t = {t_int}$")

    t_last = int(times[-1])
    ax.plot(Ns, sa[:, -1] / LN2, "x--", color="#E63946", lw=2.2,
            markersize=9, markeredgewidth=2.5, label=f"$t = {t_last}$")

    ax.set_xlabel(r"System size $N$")
    ax.set_ylabel(r"Entanglement entropy $S_{\mathrm{vN}}\,/\,\ln 2$")
    ax.set_xlim(SYSTEM_SIZES[0] - 0.5, SYSTEM_SIZES[-1] + 0.5)
    ax.set_ylim(0, SYSTEM_SIZES[-1] // 2 + 1)
    ax.set_xticks(SYSTEM_SIZES)
    ax.legend(loc="upper left", framealpha=0.9, fontsize=9)

    outpath = OUTPUT_DIR / "fig_ch5_entanglement_analog.pdf"
    fig.savefig(outpath)
    fig.savefig(outpath.with_suffix(".png"))
    print(f"    → PDF: {outpath}")
    plt.close(fig)


# ══════════════════════════════════════════════════════════════════
#  MAIN
# ══════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Chapter 5: Analog XX Model — Trotterized Evolution")
    parser.add_argument("--regenerate", action="store_true")
    parser.add_argument("--plot-only", action="store_true")
    args = parser.parse_args()

    print("=" * 65)
    print("  Chapter 5 — Analog XX Model: Trotterized Evolution")
    print("  S_A(N/2) at fixed evolution times")
    print("=" * 65)
    print(f"  System sizes: {SYSTEM_SIZES}")
    print(f"  Evolution times: {EVOLUTION_TIMES}")
    print(f"  Trotter dt = {DT} → steps: {[round(t/DT) for t in EVOLUTION_TIMES if t > 0]}")
    print(f"  JAX: {jax.default_backend()}")
    print("=" * 65)

    if args.plot_only:
        if not (DATA_DIR / "entropy_vs_N_analog.npz").exists():
            print("ERROR: data missing. Run without --plot-only first.")
            sys.exit(1)
    else:
        generate_data(regenerate=args.regenerate)

    print("\n── Figure ──")
    plot_figure()
    print(f"\nDone → {OUTPUT_DIR}")
