#!/usr/bin/env python3
"""
get_fig_ch7_qelm_spt.py
=======================
Classifying a TOPOLOGICAL (SPT) phase with a QUANTUM EXTREME LEARNING MACHINE.

Companion to get_fig_ch7_qelm_phase.py (the symmetry-breaking TFIM example).  The
point here is sharper: the phase carries NO local order parameter, so a linear
readout on the BARE low-weight observables cannot see it, yet the SAME readout on
the SCRAMBLED features succeeds.  Scrambling is what makes the topological order
locally measurable.

Produces Fig. (ch7) -- figures/ch7/fig_ch7_qelm_spt.pdf (+png).

    Panel (a): a 2D PCA of the SCRAMBLED feature vectors, coloured by the field h.
               The ground states trace a smooth arc; the cluster (SPT) and trivial
               training states sit in distinct regions and the critical point
               h_c = 1 is marked on the manifold.
    Panel (b): the trained readout's predicted trivial-phase probability
               P(trivial | h) across the sweep.  The decision crossing lands near
               h_c = 1 even though the readout trained only far from criticality;
               the held-out accuracy is annotated in-panel.
    Panel (c): the physics behind the ablation.  The nonlocal string order S(h)
               drops sharply across h_c while a representative LOCAL order
               parameter <Z_i Z_{i+1}> stays identically zero in both phases.  The
               inset bars report the two classifier accuracies: a linear readout on
               the BARE features is at chance, on the SCRAMBLED features it is high.

MODEL.  Cluster-Ising chain on an OPEN chain of N spins,
    H(h) = -J sum_i Z_{i-1} X_i Z_{i+1}  -  h sum_i X_i,
with a quantum phase transition at h/J = 1 between a symmetry-protected
TOPOLOGICAL (cluster / SPT) phase for h<1 and a trivial paramagnet for h>1.  The
protecting symmetry is Z2 x Z2, generated by the products of X on the even and the
odd sublattices.  The finite open chain has edge modes, so the cluster-phase ground
state is (near-)degenerate; we fix a unique, symmetric ground state by projecting
onto the (+1, +1) symmetry sector before diagonalizing.

WHY LOCAL OBSERVABLES FAIL.  The SPT phase breaks no symmetry, so every local order
parameter forbidden by the Z2 x Z2 symmetry (the magnetizations Z_i, Y_i and the
short correlators Z_iZ_{i+1}, Y_iY_{i+1}) vanishes IDENTICALLY in both phases.  The
order lives instead in the nonlocal string
    S = <Z_1 Y_2 X_3 ... X_{k-2} Y_{k-1} Z_k>
(the product of cluster stabilizers), which is O(1) in the SPT phase and ~0 in the
trivial phase.  A linear readout on the bare symmetry-forbidden bank therefore has
no signal and sits at chance.

WHY SCRAMBLING FIXES IT.  The reservoir is the nonintegrable MIXED-FIELD Ising
chain H_res = J_r sum Z_iZ_{i+1} + h_x sum X_i + h_z sum Z_i.  Its longitudinal
field h_z breaks BOTH the Jordan-Wigner integrability AND the cluster Z2 x Z2
symmetry.  Under U = exp(-i H_res t) a low-weight forbidden O becomes the high-weight
U^dag O U, which is no longer symmetry-forced to vanish and overlaps the string
order.  The same low-weight readout, now on the scrambled features, inherits the
nonlocal order and separates the phases.  (A symmetry-RESPECTING scrambler, however
strong, leaves the forbidden features exactly zero: it is the symmetry breaking,
not scrambling alone, that unlocks the order.)

Cached in data/ch7/fig_ch7_qelm_spt.npz.
"""
import sys
from pathlib import Path

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from scipy.linalg import expm, eigh

sys.path.insert(0, str(Path(__file__).resolve().parent))
from plot_style import apply_book_style, load_or_compute, panel_label

SCRIPT_DIR = Path(__file__).resolve().parent
OUTPUT_DIR = SCRIPT_DIR.parent / "figures" / "ch7"
DATA_DIR = SCRIPT_DIR / "data" / "ch7"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

I2 = np.eye(2, dtype=complex)
X = np.array([[0, 1], [1, 0]], dtype=complex)
Y = np.array([[0, -1j], [1j, 0]], dtype=complex)
Z = np.array([[1, 0], [0, -1]], dtype=complex)


def kron_op(single, site, N):
    op = np.array([[1.0]], dtype=complex)
    for j in range(N):
        op = np.kron(op, single if j == site else I2)
    return op


def kron_string(ops_by_site, N):
    """Full operator from a dict {site: 2x2 Pauli}, identity elsewhere."""
    op = np.array([[1.0]], dtype=complex)
    for j in range(N):
        op = np.kron(op, ops_by_site.get(j, I2))
    return op


def cluster_ising(N, J, h):
    """Cluster-Ising chain on an OPEN chain:
    H(h) = -J sum_i Z_{i-1} X_i Z_{i+1} - h sum_i X_i.
    SPT (cluster) phase for h<1, trivial paramagnet for h>1, transition at h/J=1."""
    H = np.zeros((2 ** N, 2 ** N), dtype=complex)
    for i in range(1, N - 1):
        H += -J * (kron_op(Z, i - 1, N) @ kron_op(X, i, N) @ kron_op(Z, i + 1, N))
    for i in range(N):
        H += -h * kron_op(X, i, N)
    return H


def sublattice_parity(N):
    """The two generators of the protecting Z2 x Z2 symmetry:
    P_even = prod_{i even} X_i, P_odd = prod_{i odd} X_i.  Each commutes with every
    cluster term Z_{i-1}X_iZ_{i+1} and with the transverse field, so it is a genuine
    symmetry of H(h)."""
    Pe = np.eye(2 ** N, dtype=complex)
    Po = np.eye(2 ** N, dtype=complex)
    for s in range(N):
        if s % 2 == 0:
            Pe = Pe @ kron_op(X, s, N)
        else:
            Po = Po @ kron_op(X, s, N)
    return Pe, Po


def symmetry_projector(N):
    """Projector onto the (P_even, P_odd) = (+1, +1) symmetry sector.  The open
    chain's edge modes make the cluster-phase ground state near-degenerate; fixing
    the sector selects one unique, symmetric ground state (the sector that also
    contains the trivial all-|+> state), so the string order is well defined."""
    Pe, Po = sublattice_parity(N)
    return ((np.eye(2 ** N) + Pe) / 2) @ ((np.eye(2 ** N) + Po) / 2)


def ground_state(N, J, h, Proj, lam=50.0):
    """Symmetric ground state of H(h): diagonalize H + lam (I - Proj), which lifts
    every other symmetry sector by lam and leaves the (+1,+1) sector untouched, so
    the lowest eigenvector is the unique symmetric ground state."""
    Hm = cluster_ising(N, J, h) + lam * (np.eye(2 ** N) - Proj)
    w, v = eigh(Hm)
    return v[:, 0].astype(complex)


def string_operator(N):
    """The cluster string order operator S = product of the bulk stabilizers
    K_i = Z_{i-1}X_iZ_{i+1}, which telescopes to
        Z_0 Y_1 X_2 X_3 ... X_{N-3} Y_{N-2} Z_{N-1}
    (Z on the two ends, Y just inside, X across the bulk).  <S> = 1 on the ideal
    cluster state and decays to 0 in the trivial phase."""
    ops = {0: Z, N - 1: Z, 1: Y, N - 2: Y}
    for j in range(2, N - 2):
        ops[j] = X
    return kron_string(ops, N)


def mixed_field_ising(N, Jr, hx, hz):
    """Nonintegrable mixed-field Ising reservoir
    H_res = Jr sum Z_iZ_{i+1} + hx sum X_i + hz sum Z_i.  The longitudinal hz breaks
    the integrability of the pure transverse model AND the cluster Z2 x Z2 symmetry,
    so U = exp(-i H_res t) both scrambles the state and rotates the symmetry-forbidden
    readout observables into directions that overlap the nonlocal string order."""
    H = np.zeros((2 ** N, 2 ** N), dtype=complex)
    for i in range(N - 1):
        H += Jr * (kron_op(Z, i, N) @ kron_op(Z, i + 1, N))
    for i in range(N):
        H += hx * kron_op(X, i, N) + hz * kron_op(Z, i, N)
    return H


_POP = np.array([bin(i).count("1") for i in range(1 << 16)])
_PH = np.array([1, 1j, -1, -1j])


def pauli_readout(N):
    """A FIXED bank of low-weight observables that are FORBIDDEN by the protecting
    Z2 x Z2 symmetry: the single-site magnetizations {Y_i, Z_i} and nearest-neighbour
    correlators {Y_iY_{i+1}, Z_iZ_{i+1}}.  These are exactly the conventional local
    order parameters, and because the SPT phase breaks no symmetry every one of them
    vanishes IDENTICALLY in both phases, so the bare readout carries no signal.  For a
    pure state psi a Pauli P = i^p X^x Z^z has <P> = Re sum_b conj(psi[b]) W[b]
    psi[b^x], an O(2^N) contraction (checked against brute-force <psi|P|psi>)."""
    bit = lambda i: 1 << (N - 1 - i)
    specs, names = [], []
    for i in range(N):
        specs += [(bit(i), bit(i), 1), (0, bit(i), 0)]              # Y_i, Z_i
        names += [f"Y{i}", f"Z{i}"]
    for i in range(N - 1):
        m = bit(i) | bit(i + 1)
        specs += [(m, m, 2), (0, m, 0)]                             # Y_iY_{i+1}, Z_iZ_{i+1}
        names += [f"Y{i}Y{i+1}", f"Z{i}Z{i+1}"]
    b = np.arange(1 << N)
    COLS = np.array([b ^ x for (x, z, p) in specs])
    W = np.array([_PH[p] * (1 - 2 * (_POP[z & b] & 1)) for (x, z, p) in specs],
                 dtype=complex)
    return COLS, W, names


def qelm_features(psi_list, U, COLS, W):
    """Feature matrix F (n_inputs x d).  For each ground state psi, either read the
    bank on the bare state (U is None) or on the scrambled state phi = U psi,
    f_alpha = <phi|O_alpha|phi> = <psi|U^dag O_alpha U|psi>.  Nothing here is
    trained; U and the readout set are fixed once and for all."""
    F = np.zeros((len(psi_list), COLS.shape[0]))
    for n, psi in enumerate(psi_list):
        phi = U @ psi if U is not None else psi
        F[n] = np.real(np.conj(phi) * W * phi[COLS]).sum(axis=1)
    return F


def add_shot_noise(F, shots, rng):
    """Finite-shot estimate of each Pauli expectation: variance (1 - <O>^2)/shots.
    On the bare forbidden features (true value 0) this is pure noise, so a readout
    is at chance no matter how many shots are taken; on the scrambled features the
    O(0.1) signal survives easily."""
    var = np.clip(1.0 - F ** 2, 0.0, 1.0) / shots
    return F + rng.normal(size=F.shape) * np.sqrt(var)


# ---------------------------------------------------------------------------
# Model / protocol parameters.
N = 8                        # open cluster-Ising chain (2^N = 256 dim)
J = 1.0                      # cluster coupling; critical point at h_c = J = 1
JR, HX, HZ = 1.0, 1.05, 0.5  # nonintegrable, symmetry-breaking mixed-field reservoir
T_EV = 2.5                   # fixed scrambling time in U = exp(-i H_res t)
N_SHOTS = 1024               # finite measurement shots for the bare-vs-scrambled bars
N_REAL = 60                  # shot-noise realizations averaged for the ablation

# Training fields, drawn ONLY from the clearly-SPT and clearly-trivial regions.
H_TRAIN_SPT = np.linspace(0.05, 0.55, 10)   # cluster / SPT, label 0
H_TRAIN_TRIV = np.linspace(1.45, 2.50, 10)  # trivial paramagnet, label 1
# Independent held-out fields, same clear regions, for the reported accuracy.
H_TEST_SPT = np.linspace(0.10, 0.50, 8)
H_TEST_TRIV = np.linspace(1.50, 2.45, 8)
# Dense sweep across the transition (includes the critical region) for (a)-(c).
H_SWEEP = np.linspace(0.02, 2.5, 120)


def compute():
    from sklearn.linear_model import LogisticRegression
    from sklearn.preprocessing import StandardScaler
    from sklearn.decomposition import PCA

    COLS, W, names = pauli_readout(N)
    Proj = symmetry_projector(N)
    U = expm(-1j * mixed_field_ising(N, JR, HX, HZ) * T_EV)
    Sop = string_operator(N)
    mid = N // 2
    ZZ_loc = kron_op(Z, mid, N) @ kron_op(Z, mid + 1, N)   # a local order parameter

    def states(hs):
        return [ground_state(N, J, h, Proj) for h in hs]

    h_train = np.concatenate([H_TRAIN_SPT, H_TRAIN_TRIV])
    y_train = np.concatenate([np.zeros(len(H_TRAIN_SPT)), np.ones(len(H_TRAIN_TRIV))])
    h_test = np.concatenate([H_TEST_SPT, H_TEST_TRIV])
    y_test = np.concatenate([np.zeros(len(H_TEST_SPT)), np.ones(len(H_TEST_TRIV))])

    psi_train, psi_test, psi_sweep = states(h_train), states(h_test), states(H_SWEEP)

    # Scrambled features (exact expectations) for the main classifier and PCA.
    F_train = qelm_features(psi_train, U, COLS, W)
    F_test = qelm_features(psi_test, U, COLS, W)
    F_sweep = qelm_features(psi_sweep, U, COLS, W)
    # Bare features (no reservoir): forbidden by symmetry, so ~0 to machine precision.
    B_train = qelm_features(psi_train, None, COLS, W)
    B_test = qelm_features(psi_test, None, COLS, W)

    # Standardize on the scrambled training features, fit the LINEAR (logistic) readout.
    scaler = StandardScaler().fit(F_train)
    clf = LogisticRegression(C=1.0, max_iter=5000)
    clf.fit(scaler.transform(F_train), y_train)

    acc_test = float(clf.score(scaler.transform(F_test), y_test))
    acc_train = float(clf.score(scaler.transform(F_train), y_train))
    prob_sweep = clf.predict_proba(scaler.transform(F_sweep))[:, 1]   # P(trivial)

    # Decision crossing P = 1/2 by linear interpolation of the sweep.
    cr = np.where(np.diff(np.sign(prob_sweep - 0.5)) != 0)[0]
    if len(cr):
        k = cr[0]
        p0, p1 = prob_sweep[k], prob_sweep[k + 1]
        h_cross = float(H_SWEEP[k] + (0.5 - p0) / (p1 - p0) * (H_SWEEP[k + 1] - H_SWEEP[k]))
    else:
        h_cross = float("nan")

    # 2D PCA of the scrambled feature vectors: fit on training, project everything.
    pca = PCA(n_components=2).fit(scaler.transform(F_train))
    P_train = pca.transform(scaler.transform(F_train))
    P_sweep = pca.transform(scaler.transform(F_sweep))

    # Ablation: bare vs scrambled linear-readout accuracy under identical finite-shot
    # noise, averaged over realizations.  Bare is forced to chance because the
    # forbidden features are exactly zero; scrambled inherits the string order.
    def noisy_acc(Ftr, Fte):
        rng = np.random.default_rng(0)
        accs = []
        for _ in range(N_REAL):
            Ftr_n = add_shot_noise(Ftr, N_SHOTS, rng)
            Fte_n = add_shot_noise(Fte, N_SHOTS, rng)
            sc = StandardScaler().fit(Ftr_n)
            c = LogisticRegression(C=1.0, max_iter=5000).fit(sc.transform(Ftr_n), y_train)
            accs.append(c.score(sc.transform(Fte_n), y_test))
        return float(np.mean(accs)), float(np.std(accs))

    acc_bare, acc_bare_sd = noisy_acc(B_train, B_test)
    acc_scram, acc_scram_sd = noisy_acc(F_train, F_test)

    # Physics: string order and the local order parameter across the sweep.
    S_sweep = np.array([np.vdot(p, Sop @ p).real for p in psi_sweep])
    ZZ_sweep = np.array([np.vdot(p, ZZ_loc @ p).real for p in psi_sweep])
    bare_mag = float(np.abs(B_train).max())   # size of the bare features (~1e-15)

    # Phase-averaged string order (for the printed verification).
    S_spt = float(S_sweep[H_SWEEP < 0.9].mean())
    S_triv = float(S_sweep[H_SWEEP > 1.1].mean())

    print(f"  N={N}, reservoir (Jr,hx,hz)=({JR},{HX},{HZ}), t={T_EV}, "
          f"d={F_train.shape[1]} symmetry-forbidden features")
    print(f"  string order  S(SPT h<0.9) = {S_spt:+.3f}   S(trivial h>1.1) = {S_triv:+.3f}")
    print(f"  local <Z_iZ_i+1> range over sweep: "
          f"[{ZZ_sweep.min():+.1e}, {ZZ_sweep.max():+.1e}]  (flat ~0, symmetry-forbidden)")
    print(f"  bare feature magnitude |f|max = {bare_mag:.1e}  (zero to machine precision)")
    print(f"  ablation accuracy: BARE = {acc_bare:.3f} +/- {acc_bare_sd:.3f} (chance)  "
          f"SCRAMBLED = {acc_scram:.3f} +/- {acc_scram_sd:.3f}")
    print(f"  main (scrambled) held-out accuracy = {acc_test:.3f}, "
          f"decision crossing P=1/2 at h = {h_cross:.4f}  (true h_c=1)")

    return {
        "h_train": h_train, "y_train": y_train,
        "h_sweep": H_SWEEP, "prob_sweep": prob_sweep,
        "P_train": P_train, "P_sweep": P_sweep,
        "S_sweep": S_sweep, "ZZ_sweep": ZZ_sweep,
        "acc_test": acc_test, "acc_train": acc_train, "h_cross": h_cross,
        "acc_bare": acc_bare, "acc_bare_sd": acc_bare_sd,
        "acc_scram": acc_scram, "acc_scram_sd": acc_scram_sd,
        "S_spt": S_spt, "S_triv": S_triv, "bare_mag": bare_mag,
        "evr": pca.explained_variance_ratio_, "n_shots": N_SHOTS,
        "N": N, "t_ev": T_EV,
    }


data = load_or_compute(DATA_DIR / "fig_ch7_qelm_spt.npz", compute)

h_train, y_train = data["h_train"], data["y_train"]
h_sweep, prob_sweep = data["h_sweep"], data["prob_sweep"]
P_train, P_sweep = data["P_train"], data["P_sweep"]
S_sweep, ZZ_sweep = data["S_sweep"], data["ZZ_sweep"]
acc_test, h_cross = float(data["acc_test"]), float(data["h_cross"])
acc_bare, acc_scram = float(data["acc_bare"]), float(data["acc_scram"])
S_spt, S_triv = float(data["S_spt"]), float(data["S_triv"])
evr = data["evr"]

# ---------------------------------------------------------------------------
C_SPT = "#1f6fc4"      # cluster / SPT (topological)
C_TRIV = "#c1121f"     # trivial paramagnet
C_SWEEP = "#444444"
C_GC = "#2a9d8f"
C_STR = "#1f6fc4"      # string order
C_LOC = "#c1121f"      # local order parameter

apply_book_style()
fig = plt.figure(figsize=(15.0, 4.4), constrained_layout=True)
gs = fig.add_gridspec(1, 3)
ax_a = fig.add_subplot(gs[0, 0])
ax_b = fig.add_subplot(gs[0, 1])
ax_c = fig.add_subplot(gs[0, 2])

# (a) 2D PCA of the SCRAMBLED feature vectors, coloured by the field h.  The two
#     training regions (SPT vs trivial) sit apart and the dense sweep threads
#     between them; h_c = 1 is marked on the manifold.
spt_m = y_train < 0.5
sc = ax_a.scatter(P_sweep[:, 0], P_sweep[:, 1], c=h_sweep, cmap="viridis",
                  s=30, alpha=0.85, edgecolors="none", zorder=1)
i_c = int(np.argmin(np.abs(h_sweep - 1.0)))
ax_a.plot(P_sweep[i_c, 0], P_sweep[i_c, 1], marker="*", color="black", ms=17,
          mec="white", mew=0.8, zorder=5, label=r"critical point $h_c=1$")
ax_a.scatter(P_train[spt_m, 0], P_train[spt_m, 1], s=70, color=C_SPT, marker="o",
             edgecolors="white", linewidths=0.7, zorder=3, label=r"train: SPT $h<1$")
ax_a.scatter(P_train[~spt_m, 0], P_train[~spt_m, 1], s=70, color=C_TRIV, marker="s",
             edgecolors="white", linewidths=0.7, zorder=3, label=r"train: trivial $h>1$")
ax_a.set_xlabel(f"PC 1  ({100*evr[0]:.0f}% var.)")
ax_a.set_ylabel(f"PC 2  ({100*evr[1]:.0f}% var.)")
cb = fig.colorbar(sc, ax=ax_a, pad=0.02)
cb.set_label(r"field $h$")
ax_a.legend(loc="lower left", fontsize=8, framealpha=0.92)
panel_label(ax_a, "a", loc="upper right")

# (b) predicted trivial-phase probability vs h, with the true h_c=1 marked and the
#     decision crossing annotated; held-out accuracy reported in-panel.
ax_b.axvspan(0.0, 1.0, color=C_SPT, alpha=0.06, zorder=0)
ax_b.axvspan(1.0, 2.5, color=C_TRIV, alpha=0.06, zorder=0)
ax_b.axhline(0.5, color="0.6", ls=":", lw=1.0, zorder=1)
ax_b.axvline(1.0, color=C_GC, ls="--", lw=1.5, zorder=2, label=r"true $h_c=1$")
ax_b.plot(h_sweep, prob_sweep, color=C_SWEEP, lw=2.0, zorder=3)
ax_b.plot([h_cross], [0.5], marker="o", color=C_SWEEP, ms=7, mec="white",
          mew=0.8, zorder=4)
ax_b.scatter(h_train[spt_m], np.full(spt_m.sum(), 0.02), marker="|", s=70,
             color=C_SPT, zorder=4, label="training fields")
ax_b.scatter(h_train[~spt_m], np.full((~spt_m).sum(), 0.02), marker="|", s=70,
             color=C_TRIV, zorder=4)
ax_b.set_xlabel(r"transverse field $h/J$")
ax_b.set_ylabel(r"predicted $P(\mathrm{trivial}\mid h)$")
ax_b.set_xlim(0.0, 2.5)
ax_b.set_ylim(-0.03, 1.03)
ax_b.text(0.04, 0.90,
          rf"crossing at $h={h_cross:.2f}$" + "\n" + rf"test acc. $={acc_test*100:.0f}\%$",
          transform=ax_b.transAxes, fontsize=10, va="top",
          bbox=dict(boxstyle="round,pad=0.3", fc="white", ec="0.7", alpha=0.92))
ax_b.text(0.14, 0.42, "SPT", color=C_SPT, fontsize=9, ha="center",
          transform=ax_b.transAxes)
ax_b.text(0.80, 0.58, "trivial", color=C_TRIV, fontsize=9, ha="center",
          transform=ax_b.transAxes)
ax_b.legend(loc="center right", fontsize=8, framealpha=0.92)
panel_label(ax_b, "b", loc="lower right")

# (c) the physics: the nonlocal string order S(h) drops across h_c, while the local
#     order parameter <Z_iZ_{i+1}> stays identically zero in both phases.  Inset bars
#     report the bare-vs-scrambled readout accuracy.
ax_c.axvspan(0.0, 1.0, color=C_SPT, alpha=0.06, zorder=0)
ax_c.axvspan(1.0, 2.5, color=C_TRIV, alpha=0.06, zorder=0)
ax_c.axvline(1.0, color=C_GC, ls="--", lw=1.5, zorder=2, label=r"$h_c=1$")
ax_c.plot(h_sweep, S_sweep, color=C_STR, lw=2.3, zorder=4,
          label=r"string order $S(h)$ (nonlocal)")
ax_c.plot(h_sweep, ZZ_sweep, color=C_LOC, lw=2.0, ls="-", marker="o", ms=3,
          markevery=8, zorder=3, label=r"local $\langle Z_iZ_{i+1}\rangle$")
ax_c.axhline(0.0, color="0.7", lw=0.8, zorder=1)
ax_c.set_xlabel(r"transverse field $h/J$")
ax_c.set_ylabel(r"order parameter")
ax_c.set_xlim(0.0, 2.5)
ax_c.set_ylim(-0.12, 1.08)
ax_c.legend(loc="upper right", fontsize=8, framealpha=0.92)
ax_c.text(0.035, 0.55, "SPT:\nstring order $O(1)$", color=C_SPT, fontsize=8.5,
          transform=ax_c.transAxes, va="top")

# inset: paired bars, bare vs scrambled readout accuracy
axin = ax_c.inset_axes([0.40, 0.13, 0.30, 0.42])
axin.bar([0], [acc_bare], width=0.7, color="0.6", edgecolor="black", linewidth=0.6)
axin.bar([1], [acc_scram], width=0.7, color=C_GC, edgecolor="black", linewidth=0.6)
axin.axhline(0.5, color="0.4", ls=":", lw=0.9)
axin.set_xticks([0, 1])
axin.set_xticklabels(["bare", "scram."], fontsize=7.5)
axin.set_ylim(0, 1.05)
axin.set_yticks([0.0, 0.5, 1.0])
axin.tick_params(labelsize=7)
axin.set_ylabel("acc.", fontsize=8)
axin.text(0, acc_bare + 0.04, f"{acc_bare*100:.0f}%", ha="center", fontsize=7.5)
axin.text(1, acc_scram + 0.04, f"{acc_scram*100:.0f}%", ha="center", fontsize=7.5)
axin.text(0.5, 0.56, "chance", ha="center", fontsize=6.5, color="0.4",
          transform=axin.transAxes)
panel_label(ax_c, "c", loc="upper left")

plt.savefig(OUTPUT_DIR / "fig_ch7_qelm_spt.pdf")
plt.savefig(OUTPUT_DIR / "fig_ch7_qelm_spt.png")
print(f"  string order: S(SPT)={S_spt:+.3f}, S(trivial)={S_triv:+.3f}")
print(f"  accuracies: bare={acc_bare:.3f} (chance), scrambled={acc_scram:.3f}; "
      f"main held-out={acc_test:.3f}")
print(f"  decision crossing h = {h_cross:.3f} (true h_c=1)")
print(f"  Saved: {OUTPUT_DIR / 'fig_ch7_qelm_spt.pdf'}")
