#!/usr/bin/env python3
"""
###########################################################################
#  NUMERICAL EXERCISE -- Randomized Benchmarking via Clifford Twirling
#
#  Chapter 6, Applications
#  Topic: Twirling, depolarizing channel, average gate fidelity,
#         randomized benchmarking protocol
#
#  ---------- EXERCISE STATEMENT ----------
#
#  Randomized benchmarking (RB) extracts the average gate fidelity
#  of a noisy Clifford gate set by measuring the survival probability
#  of a reference state as a function of sequence length m.
#
#  Protocol:
#    1. For each sequence length m, repeat n_seq times:
#       (a) Draw m random Clifford gates C_1, ..., C_m.
#       (b) Compute the recovery gate C_{m+1} = (C_m ... C_1)^{-1}.
#       (c) Apply noisy versions of C_1, ..., C_m, C_{m+1} to |0>.
#       (d) Measure the survival probability p = |<0|psi_final>|^2.
#    2. Average over sequences: p_bar(m).
#    3. Fit p_bar(m) = A * alpha^m + B to extract the depolarizing
#       parameter alpha.  The average gate fidelity is:
#       F_avg = alpha + (1 - alpha)/D,  where D = 2^N.
#
#  Tasks:
#    (a) Implement the single-qubit Clifford group (24 elements).
#    (b) Implement a noise model: depolarizing channel with error p.
#    (c) Run the RB protocol for several sequence lengths.
#    (d) Fit the exponential decay and extract F_avg.
#    (e) Verify the twirling identity: Clifford twirl of ANY channel
#        yields a depolarizing channel.
#
#  ---------- ANALYTICAL BACKGROUND ----------
#
#  Twirling theorem:
#    E_C[C Lambda C^{-1}] = p * id + (1-p) * D_depol
#
#  where Lambda is any CPTP map, the average is over the Clifford group,
#  and D_depol(rho) = Tr(rho) * I/D is the completely depolarizing channel.
#
#  The parameter p depends on Lambda through:
#    p = (D * F_avg(Lambda) - 1) / (D - 1)
#
#  where F_avg = integral dPsi <Psi|Lambda(|Psi><Psi|)|Psi>.
#
#  RB exploits the fact that composing m twirled channels gives:
#    p_bar(m) = A * p^m + B
#  so a single exponential fit extracts p (and hence F_avg).
#
#  ---------- NUMERICAL SOLUTION ----------
###########################################################################
"""
import numpy as np
from scipy.optimize import curve_fit

np.random.seed(42)

# ========================================================================
# Part (a): Construct the single-qubit Clifford group (24 elements)
# ========================================================================
print("Part (a): Constructing the single-qubit Clifford group")
print("=" * 60)

# Generators: Hadamard H and Phase gate S
H = np.array([[1, 1], [1, -1]], dtype=complex) / np.sqrt(2)
S = np.array([[1, 0], [0, 1j]], dtype=complex)
I2 = np.eye(2, dtype=complex)

# Generate all 24 Cliffords by composing H and S
# The single-qubit Clifford group is generated by H and S,
# with relations H^2 = I, S^4 = I, (HS)^3 = phase * I.
def generate_cliffords():
    """Generate all 24 single-qubit Clifford unitaries."""
    cliffords = set()
    result = []
    queue = [I2.copy()]

    while queue:
        U = queue.pop(0)
        # Round to avoid floating-point duplicates
        key = tuple(np.round(U.flatten(), 8))
        if key in cliffords:
            continue
        cliffords.add(key)
        result.append(U)

        if len(result) >= 24:
            break

        for gate in [H, S]:
            new = gate @ U
            # Normalize global phase (fix first nonzero entry to be real+positive)
            for entry in new.flatten():
                if abs(entry) > 1e-10:
                    new = new * np.exp(-1j * np.angle(entry))
                    break
            queue.append(new)

    return result

cliffords_1q = generate_cliffords()
print(f"  Generated {len(cliffords_1q)} single-qubit Clifford unitaries")

# If we got fewer than 24, supplement with products
while len(cliffords_1q) < 24:
    for C1 in list(cliffords_1q):
        for C2 in list(cliffords_1q):
            U = C1 @ C2
            for entry in U.flatten():
                if abs(entry) > 1e-10:
                    U = U * np.exp(-1j * np.angle(entry))
                    break
            is_new = True
            for existing in cliffords_1q:
                if np.allclose(U, existing, atol=1e-6):
                    is_new = False
                    break
            if is_new:
                cliffords_1q.append(U)
            if len(cliffords_1q) >= 24:
                break
        if len(cliffords_1q) >= 24:
            break

print(f"  Final count: {len(cliffords_1q)} Cliffords")

# ========================================================================
# Part (b): Depolarizing noise model
# ========================================================================
print(f"\nPart (b): Noise model -- depolarizing channel with error rate p")
print("=" * 60)

sx = np.array([[0, 1], [1, 0]], dtype=complex)
sy = np.array([[0, -1j], [1j, 0]], dtype=complex)
sz = np.array([[1, 0], [0, -1]], dtype=complex)

def apply_depolarizing(rho, p_dep):
    """Single-qubit depolarizing channel in the uniform (I/d) convention,
    matching the exercise statement: E(rho) = (1 - p_dep)*rho + p_dep*I/d.
    For d = 2 the depolarizing parameter (contraction of the traceless part)
    is alpha = 1 - p_dep."""
    d = rho.shape[0]
    return (1 - p_dep) * rho + p_dep * np.eye(d, dtype=complex) / d

def noisy_gate(U, rho, p_error):
    """Apply a unitary gate followed by depolarizing noise."""
    rho_out = U @ rho @ U.conj().T
    return apply_depolarizing(rho_out, p_error)

# Verify the channel is trace-preserving
rho_test = np.array([[0.7, 0.3j], [-0.3j, 0.3]], dtype=complex)
for p_error in [0.0, 0.01, 0.1]:
    rho_out = apply_depolarizing(rho_test, p_error)
    tr = np.trace(rho_out).real
    print(f"  p={p_error:.2f}: Tr(E(rho)) = {tr:.10f}  [trace-preserving]")
    assert abs(tr - 1.0) < 1e-12

# ========================================================================
# Part (c): Run the RB protocol
# ========================================================================
print(f"\nPart (c): Running the RB protocol")
print("=" * 60)

p_error = 0.01  # depolarizing error per gate (p_dep in the exercise statement)
n_seq = 200     # number of random sequences per length
sequence_lengths = [1, 2, 4, 8, 16, 24, 32, 40, 50]

psi0 = np.array([1, 0], dtype=complex)
rho0 = np.outer(psi0, psi0.conj())

survival_probs = []

for m in sequence_lengths:
    survivals = []
    for _ in range(n_seq):
        # Draw m random Cliffords
        indices = np.random.randint(0, len(cliffords_1q), size=m)
        gates = [cliffords_1q[i] for i in indices]

        # Compute ideal total unitary: U_total = C_m ... C_1
        U_total = np.eye(2, dtype=complex)
        for C in gates:
            U_total = C @ U_total

        # Recovery gate: C_{m+1} = U_total^{-1}
        C_recovery = U_total.conj().T

        # Apply noisy sequence
        rho = rho0.copy()
        for C in gates:
            rho = noisy_gate(C, rho, p_error)
        rho = noisy_gate(C_recovery, rho, p_error)

        # Survival probability
        p_surv = (psi0.conj() @ rho @ psi0).real
        survivals.append(p_surv)

    p_bar = np.mean(survivals)
    survival_probs.append(p_bar)
    print(f"  m={m:4d}: p_bar = {p_bar:.4f}")

# ========================================================================
# Part (d): Fit the exponential decay and extract F_avg
# ========================================================================
print(f"\nPart (d): Fitting p_bar(m) = A * alpha^m + B")
print("=" * 60)

def rb_model(m, A, alpha, B):
    return A * alpha**m + B

ms = np.array(sequence_lengths, dtype=float)
ps = np.array(survival_probs)

popt, pcov = curve_fit(rb_model, ms, ps, p0=[0.5, 0.98, 0.5], maxfev=10000)
A_fit, alpha_fit, B_fit = popt

D = 2  # single qubit
F_avg = alpha_fit + (1 - alpha_fit) / D

# Theoretical prediction for the IMPLEMENTED channel (see apply_depolarizing):
#   E(rho) = (1 - p_dep)*rho + p_dep*I/d,  p_dep = p_error.
# This is the uniform (I/d-form) depolarizing channel used in the exercise.
# Its depolarizing parameter (the factor multiplying the traceless part of
# rho) is alpha = 1 - p_dep. Hence for D = 2:
#   alpha = 1 - p_dep,  F_avg = (1 + (D-1)*alpha)/D = (1 + alpha)/2 = 1 - p_dep/2.
# With p_dep = 0.01 this gives alpha = 0.99, F_avg = 0.995, matching the
# worked solution (F(50) ~ 0.5 + 0.5*0.99^50 ~ 0.803).
alpha_theory = 1 - p_error
F_avg_theory = 1 - p_error / 2

print(f"  Fit:    A = {A_fit:.4f}, alpha = {alpha_fit:.4f}, B = {B_fit:.4f}")
print(f"  alpha_fit    = {alpha_fit:.6f}  (theory: {alpha_theory:.6f})")
print(f"  F_avg(fit)   = {F_avg:.6f}  (theory: {F_avg_theory:.6f})")
print(f"  Error rate p = {p_error:.4f}")

# ========================================================================
# Part (e): Verify the twirling identity
# ========================================================================
print(f"\nPart (e): Twirling identity -- any channel -> depolarizing")
print("=" * 60)

# Apply a NON-depolarizing channel (e.g., amplitude damping)
# then twirl over the Clifford group.

gamma = 0.1  # amplitude damping parameter
K0_ad = np.array([[1, 0], [0, np.sqrt(1-gamma)]], dtype=complex)
K1_ad = np.array([[0, np.sqrt(gamma)], [0, 0]], dtype=complex)

def amp_damp(rho):
    return K0_ad @ rho @ K0_ad.conj().T + K1_ad @ rho @ K1_ad.conj().T

# Twirl: E_twirled(rho) = (1/|C|) sum_C C^dag Lambda(C rho C^dag) C
def twirled_channel(rho, channel_fn, clifford_list):
    result = np.zeros_like(rho)
    for C in clifford_list:
        rotated = C @ rho @ C.conj().T
        noisy = channel_fn(rotated)
        unrotated = C.conj().T @ noisy @ C
        result += unrotated
    return result / len(clifford_list)

# The twirled channel should be depolarizing:
# E_twirl(rho) = p * rho + (1-p) * I/2
# Test on several input states
for label, test_rho in [
    ("|0><0|", np.array([[1,0],[0,0]], dtype=complex)),
    ("|+><+|", np.array([[0.5,0.5],[0.5,0.5]], dtype=complex)),
    ("mixed",  np.array([[0.7,0.2j],[-0.2j,0.3]], dtype=complex)),
]:
    out = twirled_channel(test_rho, amp_damp, cliffords_1q)

    # Check if output = p*test_rho + (1-p)*I/2 for some p
    # Solve: out = p*test_rho + (1-p)*I/2
    # out - I/2 = p*(test_rho - I/2)
    diff_out = out - I2/2
    diff_in = test_rho - I2/2
    # Find p from non-zero elements
    mask = np.abs(diff_in) > 1e-10
    if mask.any():
        p_vals = diff_out[mask] / diff_in[mask]
        p_est = np.mean(p_vals.real)
        p_spread = np.std(p_vals.real)
        print(f"  {label:10s}: p = {p_est:.6f} +/- {p_spread:.2e}  "
              f"[{'depolarizing' if p_spread < 0.01 else 'NOT depolarizing'}]")

print(f"\n  The Clifford twirl converts the amplitude damping channel")
print(f"  (which is NOT depolarizing and NOT unital) into a")
print(f"  depolarizing channel.  This is the mathematical foundation")
print(f"  of randomized benchmarking: regardless of the physical noise,")
print(f"  the twirled effective channel is always depolarizing, and its")
print(f"  strength is characterized by a single parameter alpha.")
